### ISSUE TITLE
Vanity Link not working

### ISSUE THREAD

**Issue by greenfelt22** [reecesavage/nova-ext-url-parser#2]
The vanity link for the URL Parser is not functional:
![image](https://user-images.githubusercontent.com/25126048/111399618-b4689780-8693-11eb-9910-39d776c13aab.png)

I also tried removing the spaces to no effect.

**Comment by reecesavage** [comment]
@greenfelt22 are you putting these in a post or somewhere else? I wasn't able to duplicate it with a mission post. 

![image](https://user-images.githubusercontent.com/15860882/111400699-dc58fa80-8695-11eb-86bc-8f2896685ec2.png)

**Comment by greenfelt22** [comment]
This was in an unpublished mission post. The screenshot is what was sent to my email from Nova.

**Comment by reecesavage** [comment]
Thanks, @greenfelt22! I have duplicated the issue.

![image](https://user-images.githubusercontent.com/15860882/111401569-86855200-8697-11eb-9a84-8acda057c65f.png)

@pawanmall157 please check this bug.

**Comment by pawanmall157** [comment]
Fixed

**Comment by reecesavage** [comment]
Fixed in v1.0.1
